### ISSUE TITLE
svelte formatter broken with minimal install

### ISSUE THREAD

**Issue by Malix-Labs** [sveltejs/cli#216]
## Reproduction

```sh
codespace:/workspaces/sveltekit-on-deno> npx sv create
┌  Welcome to the Svelte CLI! (v0.5.7)
│
◇  Where would you like your project to be created?
│  ./
│
◇  Directory not empty. Continue?
│  Yes
│
◇  Which template would you like?
│  SvelteKit minimal
│
◇  Add type checking with Typescript?
│  Yes, using Typescript syntax
│
◆  Project created
│
◇  What would you like to add to your project?
│  none
│
◇  Which package manager do you want to install dependencies with?
│  npm
│
◇  Successfully installed dependencies
│
◇  Project next steps ─────────────────────────────────────────────────────╮
│                                                                          │
│  1: git init && git add -A && git commit -m "Initial commit" (optional)  │
│  2: npm run dev -- --open                                                │
│                                                                          │
│  To close the dev server, hit Ctrl-C                                     │
│                                                                          │
│  Stuck? Visit us at https://svelte.dev/chat                              │
│                                                                          │
├──────────────────────────────────────────────────────────────────────────╯
│
└  You're all set!
```

## Subject

`src/routes/+layout.svelte`
```svelte
<script lang="ts">
	import '../app.css';
	let { children } = $props();
</script>

	{@render children()}
```

## Logs

```log
CompileError [ParseError]: Unexpected character '@'
  1 | <script lang="ts">
  2 | 	import '../app.css';
> 3 | 	let { children } = $props();
    | 	^
  4 | </script>
  5 |
  6 | 	{@render children()}
    at error (/home/vscode/.vscode-server/extensions/svelte.svelte-vscode-109.1.0/node_modules/svelte/compiler.cjs:14256:16)
    at Parser.error (/home/vscode/.vscode-server/extensions/svelte.svelte-vscode-109.1.0/node_modules/svelte/compiler.cjs:14404:3)
    at Parser.acorn_error (/home/vscode/.vscode-server/extensions/svelte.svelte-vscode-109.1.0/node_modules/svelte/compiler.cjs:14391:8)
    at read_expression (/home/vscode/.vscode-server/extensions/svelte.svelte-vscode-109.1.0/node_modules/svelte/compiler.cjs:9641:10)
    at mustache (/home/vscode/.vscode-server/extensions/svelte.svelte-vscode-109.1.0/node_modules/svelte/compiler.cjs:13965:22)
    at new Parser (/home/vscode/.vscode-server/extensions/svelte.svelte-vscode-109.1.0/node_modules/svelte/compiler.cjs:14352:12)
    at Object.parse (/home/vscode/.vscode-server/extensions/svelte.svelte-vscode-109.1.0/node_modules/svelte/compiler.cjs:14529:17)
    at Object.parse (/home/vscode/.vscode-server/extensions/svelte.svelte-vscode-109.1.0/node_modules/prettier-plugin-svelte/plugin.js:2300:65)
    at parse4 (file:///home/vscode/.vscode-server/extensions/svelte.svelte-vscode-109.1.0/node_modules/prettier/index.mjs:20685:24)
    at async coreFormat (file:///home/vscode/.vscode-server/extensions/svelte.svelte-vscode-109.1.0/node_modules/prettier/index.mjs:21146:7) {
  code: 'parse-error',
  start: { line: 3, column: 2, character: 127 },
  end: { line: 3, column: 2, character: 127 },
  pos: 127,
  filename: undefined,
  frame: '1: <script lang="ts" ✂prettier:content✂="CglpbXBvcnQgJy4uL2FwcC5jc3MnOwoJbGV0IHsgY2hpbGRyZW4gfSA9ICRwcm9wcygpOwo=">{}</script>\n' +
    '2: \n' +
    '3:   {@render children()}\n' +
    '      ^',
  loc: {
    start: { line: 3, column: 2, character: 127 },
    end: { line: 3, column: 2, character: 127 }
  },
  codeFrame: '  1 | <script lang="ts">\n' +
    "  2 | \timport '../app.css';\n" +
    '> 3 | \tlet { children } = $props();\n' +
    '    | \t^\n' +
    '  4 | </script>\n' +
    '  5 |\n' +
    '  6 | \t{@render children()}'
}
```

## Config

- VSCode@1.94.2
- svelte.svelte-vscode@109.1.0
- sv@0.5.7

**Comment by Conduitry** [comment]
Judging by the stack trace, you are formatting with the VS Code extension, which is using its own embedded version of Prettier and the Svelte Prettier plugin, because you don't have Prettier installed or configured locally - and the embedded copy is still Svelte 4. At some point, that's probably going to change, but in the meantime, see https://github.com/sveltejs/prettier-plugin-svelte#prettier-plugin for how to explicitly configure Prettier.

**Comment by Malix-Labs** [comment]
Thanks for that fast explanation @Conduitry !

> At some point, that's probably going to change

Is there any issue I can track about that ?
