### ISSUE TITLE
Default Drizzle + Local postgres configuration throws "PostgresError: role "root" does not exist"

### ISSUE THREAD

**Issue by mjdanbury** [sveltejs/cli#331]
The default Drizzle + Local postgres starter that the CLI creates currently throws "PostgresError: role "root" does not exist" upon running `npm run db:push`:

## Run the CLI
```
npx sv create MRE
Need to install the following packages:
sv@0.6.5
Ok to proceed? (y) y
┌  Welcome to the Svelte CLI! (v0.6.5)
│
◇  Which template would you like?
│  SvelteKit minimal
│
◇  Add type checking with Typescript?
│  Yes, using Typescript syntax
│
◆  Project created
│
◇  What would you like to add to your project? (use arrow keys / space bar)
│  prettier, eslint, drizzle, lucia
│
◇  drizzle: Which database would you like to use?
│  PostgreSQL
│
◇  drizzle: Which PostgreSQL client would you like to use?
│  Postgres.JS
│
◇  drizzle: Do you want to run the database locally with docker-compose?
│  Yes
│
◇  lucia: Do you want to include a demo? (includes a login/register page)
│  Yes
│
◇  Which package manager do you want to install dependencies with?
│  npm
│
◆  Successfully setup add-ons
│
◆  Successfully installed dependencies
│
◇  Successfully formatted modified files
│
◇  Project next steps ─────────────────────────────────────────────────────╮
│                                                                          │
│  1: cd MRE                                                               │
│  2: git init && git add -A && git commit -m "Initial commit" (optional)  │
│  3: npm run dev -- --open                                                │
│                                                                          │
│  To close the dev server, hit Ctrl-C                                     │
│                                                                          │
│  Stuck? Visit us at https://svelte.dev/chat                              │
│                                                                          │
├──────────────────────────────────────────────────────────────────────────╯
│
◇  Add-on next steps ──────────────────────────────────────────────────╮
│                                                                      │
│  drizzle:                                                            │
│  - You will need to set DATABASE_URL in your production environment  │
│  - Run npm run db:start to start the docker container                │
│  - Run npm run db:push to update your database schema                │
│                                                                      │
│  lucia:                                                              │
│  - Run npm run db:push to update your database schema                │
│  - Visit /demo/lucia route to view the demo                          │
│                                                                      │
├──────────────────────────────────────────────────────────────────────╯
│
└  You're all set!
```
## Running db:start works

```
matthew@Matthews-MacBook-Pro-9 MRE % npm run db:start

> mre@0.0.1 db:start
> docker compose up

Attaching to db-1
db-1  | The files belonging to this database system will be owned by user "postgres".
db-1  | This user must also own the server process.
db-1  | 
db-1  | The database cluster will be initialized with locale "en_US.utf8".
db-1  | The default database encoding has accordingly been set to "UTF8".
db-1  | The default text search configuration will be set to "english".
db-1  | 
db-1  | Data page checksums are disabled.
db-1  | 
db-1  | fixing permissions on existing directory /var/lib/postgresql/data ... ok
db-1  | creating subdirectories ... ok
db-1  | selecting dynamic shared memory implementation ... posix
db-1  | selecting default "max_connections" ... 100
db-1  | selecting default "shared_buffers" ... 128MB
db-1  | selecting default time zone ... Etc/UTC
db-1  | creating configuration files ... ok
db-1  | running bootstrap script ... ok
db-1  | performing post-bootstrap initialization ... ok
db-1  | initdb: warning: enabling "trust" authentication for local connections
db-1  | initdb: hint: You can change this by editing pg_hba.conf or using the option -A, or --auth-local and --auth-host, the next time you run initdb.
db-1  | syncing data to disk ... ok
db-1  | 
db-1  | 
db-1  | Success. You can now start the database server using:
db-1  | 
db-1  |     pg_ctl -D /var/lib/postgresql/data -l logfile start
db-1  | 
db-1  | waiting for server to start....2024-11-26 19:16:25.639 UTC [48] LOG:  starting PostgreSQL 17.2 (Debian 17.2-1.pgdg120+1) on aarch64-unknown-linux-gnu, compiled by gcc (Debian 12.2.0-14) 12.2.0, 64-bit
db-1  | 2024-11-26 19:16:25.640 UTC [48] LOG:  listening on Unix socket "/var/run/postgresql/.s.PGSQL.5432"
db-1  | 2024-11-26 19:16:25.642 UTC [51] LOG:  database system was shut down at 2024-11-26 19:16:25 UTC
db-1  | 2024-11-26 19:16:25.644 UTC [48] LOG:  database system is ready to accept connections
db-1  |  done
db-1  | server started
db-1  | CREATE DATABASE
db-1  | 
db-1  | 
db-1  | /usr/local/bin/docker-entrypoint.sh: ignoring /docker-entrypoint-initdb.d/*
db-1  | 
db-1  | waiting for server to shut down....2024-11-26 19:16:25.792 UTC [48] LOG:  received fast shutdown request
db-1  | 2024-11-26 19:16:25.793 UTC [48] LOG:  aborting any active transactions
db-1  | 2024-11-26 19:16:25.794 UTC [48] LOG:  background worker "logical replication launcher" (PID 54) exited with exit code 1
db-1  | 2024-11-26 19:16:25.794 UTC [49] LOG:  shutting down
db-1  | 2024-11-26 19:16:25.795 UTC [49] LOG:  checkpoint starting: shutdown immediate
db-1  | 2024-11-26 19:16:25.820 UTC [49] LOG:  checkpoint complete: wrote 921 buffers (5.6%); 0 WAL file(s) added, 0 removed, 0 recycled; write=0.009 s, sync=0.015 s, total=0.026 s; sync files=301, longest=0.004 s, average=0.001 s; distance=4238 kB, estimate=4238 kB; lsn=0/1908948, redo lsn=0/1908948
db-1  | 2024-11-26 19:16:25.824 UTC [48] LOG:  database system is shut down
db-1  |  done
db-1  | server stopped
db-1  | 
db-1  | PostgreSQL init process complete; ready for start up.
db-1  | 
db-1  | 2024-11-26 19:16:25.908 UTC [1] LOG:  starting PostgreSQL 17.2 (Debian 17.2-1.pgdg120+1) on aarch64-unknown-linux-gnu, compiled by gcc (Debian 12.2.0-14) 12.2.0, 64-bit
db-1  | 2024-11-26 19:16:25.908 UTC [1] LOG:  listening on IPv4 address "0.0.0.0", port 5432
db-1  | 2024-11-26 19:16:25.908 UTC [1] LOG:  listening on IPv6 address "::", port 5432
db-1  | 2024-11-26 19:16:25.909 UTC [1] LOG:  listening on Unix socket "/var/run/postgresql/.s.PGSQL.5432"
db-1  | 2024-11-26 19:16:25.911 UTC [64] LOG:  database system was shut down at 2024-11-26 19:16:25 UTC
db-1  | 2024-11-26 19:16:25.914 UTC [1] LOG:  database system is ready to accept connections
db-1  | 2024-11-26 19:21:26.009 UTC [62] LOG:  checkpoint starting: time
db-1  | 2024-11-26 19:21:30.562 UTC [62] LOG:  checkpoint complete: wrote 47 buffers (0.3%); 0 WAL file(s) added, 0 removed, 0 recycled; write=4.530 s, sync=0.011 s, total=4.553 s; sync files=12, longest=0.007 s, average=0.001 s; distance=269 kB, estimate=269 kB; lsn=0/194C028, redo lsn=0/194BFB8
```
## Running db:push throws the error

```
matthew@Matthews-MacBook-Pro-9 MRE % npm run db:push

> mre@0.0.1 db:push
> drizzle-kit push

drizzle-kit: v0.22.8
drizzle-orm: v0.33.0

No config path provided, using default path
Reading config file '/Users/matthew/Developer/MRE/drizzle.config.ts'
Using 'postgres' driver for database querying
[⣷] Pulling schema from database...
PostgresError: role "root" does not exist
    at ErrorResponse (/Users/matthew/Developer/MRE/node_modules/drizzle-kit/bin.cjs:79677:27)
    at handle (/Users/matthew/Developer/MRE/node_modules/drizzle-kit/bin.cjs:79454:7)
    at Socket.data (/Users/matthew/Developer/MRE/node_modules/drizzle-kit/bin.cjs:79277:9)
    at Socket.emit (node:events:514:28)
    at addChunk (node:internal/streams/readable:545:12)
    at readableAddChunkPushByteMode (node:internal/streams/readable:495:3)
    at Readable.push (node:internal/streams/readable:375:5)
    at TCP.onStreamRead (node:internal/stream_base_commons:190:23)
    at TCP.callbackTrampoline (node:internal/async_hooks:130:17) {
  severity_local: 'FATAL',
  severity: 'FATAL',
  code: '28000',
  file: 'miscinit.c',
  line: '752',
  routine: 'InitializeSessionUserId'
}
```

**Comment by mjdanbury** [comment]
Oops! This was happening because I had homebrew postgres running on the same port. If you find yourself in this situation, you can run `brew services list` followed by `brew services stop <service>`. After doing this, `npm run db:push` works as it should.
