### ISSUE TITLE
ESBuild errors starting dev server on new project with drizzle and auth enabled

### ISSUE THREAD

**Issue by oluijks** [sveltejs/cli#366]
Creating a brand new project with drizzle and lucia auth gives me this error when starting the dev server. I've tested this on a bunch of different nodejs versions. I tried deleting node_modules and .svelte-kit dirs and cleared pnpm cache.

I could not find any related issues in the esbuild package.

```sh
> vite dev "--host" "0.0.0.0"

✘ [ERROR] Expected identifier but found "import"

    (define name):1:0:
      1 │ import.meta.dirname
        ╵ ~~~~~~

✘ [ERROR] Expected identifier but found "import"

    (define name):1:0:
      1 │ import.meta.filename
        ╵ ~~~~~~

✘ [ERROR] Expected identifier but found "import"

    (define name):1:0:
      1 │ import.meta.url
        ╵ ~~~~~~

failed to load config from /home/oluijks/Code/test-auth-drizzle/vite.config.ts
error when starting dev server:
Error: Build failed with 3 errors:
(define name):1:0: ERROR: Expected identifier but found "import"
(define name):1:0: ERROR: Expected identifier but found "import"
(define name):1:0: ERROR: Expected identifier but found "import"
    at failureErrorWithLog (/home/oluijks/Code/test-auth-drizzle/node_modules/.pnpm/esbuild@0.24.1/node_modules/esbuild/lib/main.js:1476:15)
    at /home/oluijks/Code/test-auth-drizzle/node_modules/.pnpm/esbuild@0.24.1/node_modules/esbuild/lib/main.js:945:25
    at runOnEndCallbacks (/home/oluijks/Code/test-auth-drizzle/node_modules/.pnpm/esbuild@0.24.1/node_modules/esbuild/lib/main.js:1316:45)
    at buildResponseToResult (/home/oluijks/Code/test-auth-drizzle/node_modules/.pnpm/esbuild@0.24.1/node_modules/esbuild/lib/main.js:943:7)
    at /home/oluijks/Code/test-auth-drizzle/node_modules/.pnpm/esbuild@0.24.1/node_modules/esbuild/lib/main.js:970:16
    at responseCallbacks.<computed> (/home/oluijks/Code/test-auth-drizzle/node_modules/.pnpm/esbuild@0.24.1/node_modules/esbuild/lib/main.js:622:9)
    at handleIncomingPacket (/home/oluijks/Code/test-auth-drizzle/node_modules/.pnpm/esbuild@0.24.1/node_modules/esbuild/lib/main.js:677:12)
    at Socket.readFromStdout (/home/oluijks/Code/test-auth-drizzle/node_modules/.pnpm/esbuild@0.24.1/node_modules/esbuild/lib/main.js:600:7)
    at Socket.emit (node:events:524:28)
    at addChunk (node:internal/streams/readable:561:12)
 ELIFECYCLE  Command failed with exit code 1.
```

```
System:
  OS: Linux 6.12 Arch Linux
  CPU: (16) x64 13th Gen Intel(R) Core(TM) i7-1360P
  Memory: 7.46 GB / 15.21 GB
  Container: Yes
  Shell: 5.9 - /bin/zsh
Binaries:
  Node: 22.12.0 - ~/.nvm/versions/node/v22.12.0/bin/node
  npm: 10.9.0 - ~/.nvm/versions/node/v22.12.0/bin/npm
  pnpm: 9.14.4 - ~/.local/share/pnpm/pnpm
  bun: 1.1.37 - ~/.bun/bin/bun
Browsers:
  Chromium: 131.0.6778.204
npmPackages:
  @sveltejs/adapter-auto: ^3.0.0 => 3.3.1 
  @sveltejs/kit: ^2.9.0 => 2.13.0 
  @sveltejs/vite-plugin-svelte: ^5.0.0 => 5.0.3 
  svelte: ^5.0.0 => 5.15.0 
  vite: ^6.0.0 => 6.0.4 
```

**Comment by oluijks** [comment]
> Seems to be an issue with esbuild 0.24.1 just released one hour ago. Resolved with this in package.json:
> 
> ```
> 	"overrides": {
> 		"esbuild": "0.24.0"
> 	}
> ```

I think I missed the update from an hour ago. Yes, overriding esbuild to 0.24.0 works.

**Comment by dominikg** [comment]
vite 6.0.5 pinned esbuild to 0.24.0, we are going to unpin esbuild after the fix has been released. this step has been taken to reduce the number of affected users and make it easier than adding a local override.

i'll close this issue as regular update flow get people out of it, still recommend interested parties to follow esbuild and vite release notes over the next hours/days.
